VELPUS_AUTH = 1
VELPUS_CONNECT = 2
VELPUS_SEND = 3
VELPUS_RECV = 4
VELPUS_DISCONNECT = 5

VELPUS_IPV4 = 6
VELPUS_ALLMSG = 7
VELPUS_ERRMSGONLY = 8

VELPUS_SUCCEED = 9
VELPUS_FAILED = 10
VELPUS_CONNECTION_TIMEOUT = 11
VELPUS_INVALID_CMD = 12
VELPUS_INVALID_UUID = 13
VELPUS_INVALID_ADDR = 14