class CMD:
    VELPUS_CONNECT = 1
    VELPUS_SEND = 2
    VELPUS_RECV = 3
    VELPUS_DISCONNECT = 4

class TYPE:
    VELPUS_IPV4 = 1

class MSG:
    VELPUS_SUCCEED = 1
    VELPUS_INVALID_UUID = 2
    VELPUS_UNSUPPORTED_ATYPE = 3
    VELPUS_TIMEOUT = 4
    VELPUS_UNCONNECTED = 5
    VELPUS_UNAUTHORIZED = 6
    VELPUS_UNKNOWN_CMD = 7