class CMD:
    VELPUS_AUTH = 1
    VELPUS_CONNECT = 2
    VELPUS_SEND = 3
    VELPUS_RECV = 4
    VELPUS_DISCONNECT = 5
    VELPUS_MSG = 6

class TYPE:
    VELPUS_IPV4 = 1
    VELPUS_ALLMSG = 2
    VELPUS_ERRMSGONLY = 3

class MSG:
    VELPUS_SUCCEED = 1
    VELPUS_FAILED = 2
    VELPUS_INVALID_UUID = 3
    VELPUS_CONNECTION_TIMEOUT = 4
    VELPUS_UNCONNECTED = 5
    VELPUS_UNKNOWN_CMD = 6